catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.16
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.16
  vite-plus: 0.1.16
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
